# Generated by Django 5.0.2 on 2024-02-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('limite', models.IntegerField(default=0, null=True)),
                ('saldo', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
                ('descricao', models.CharField(default='descricao', max_length=10)),
                ('realizada_em', models.DateTimeField()),
                ('status', models.CharField(default='ERRO', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
